version: '3'

services:
  postgres_db:
    image: postgres:latest
    restart: "on-failure"
    volumes:
      - /home/dashboard/postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=oscloud
      - POSTGRES_USER=oscloud
      - POSTGRES_PASSWORD=oscloud
    ports:
      - 5432:5432
    networks:
      - oscould_network

  backend:
    build:
      context: ./backend
      dockerfile: docker-prod-backend.Dockerfile
    restart: "on-failure"
    volumes:
      - ./backend:/app
    environment:
      - ENV_NAME=production
      - DEFAULT_PORT=8000
      - DEBUG=False
      - SECRET_KEY="django-insecure-d(#b+7*or_a$36@5io@o&5w1f@73&%2_m6r!e0o^4q=(@*8&#1"
      - ALLOWED_HOSTS=192.168.1.105
      - DEFAULT_DB_ENGINE=django.db.backends.postgresql
      - DEFAULT_DB_NAME=oscloud
      - DEFAULT_DB_USERNAME=oscloud
      - DEFAULT_DB_PASSWORD=oscloud
      - DEFAULT_DB_HOST=postgres_db
      - DEFAULT_DB_PORT=5432
      - ACCESS_TOKEN_LIFETIME_MIN=360
      - REFRESH_TOKEN_LIFETIME_HOUR=24
    ports:
      - 8000:8000
    networks:
      - oscould_network
    depends_on:
      - postgres_db

  nginx:
    build:
      context: ./frontend
      dockerfile: docker-nginx.Dockerfile
    environment:
      - NODE_ENV=production
    ports:
      - 80:80
    depends_on:
      - backend
    networks:
      - oscould_network

networks:
  oscould_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.0.0/24
